# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-09 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=3000)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
    ]
